# -*- coding: utf-8 -*-
"""TUGAS 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGf4Gd7atV581G2oOv10OgEVa6AGJvqf
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
import ipywidgets as widgets
from IPython.display import display

def sird_model(y, t, N, beta, gamma, mu):
    S, I, R, D = y
    dSdt = -beta * S * I / N
    dIdt = beta * S * I / N - gamma * I - mu * I
    dRdt = gamma * I
    dDdt = mu * I
    return [dSdt, dIdt, dRdt, dDdt]

def update_sird(beta, gamma, mu, S0, I0, Tmax):
    N = S0 + I0
    R0, D0 = 0, 0
    t = np.linspace(0, Tmax, Tmax)

    y0 = [S0, I0, R0, D0]
    solution = odeint(sird_model, y0, t, args=(N, beta, gamma, mu))
    S, I, R, D = solution.T

    plt.figure(figsize=(10, 6))
    plt.plot(t, S, label='Susceptible', color='blue')
    plt.plot(t, I, label='Infected', color='orange')
    plt.plot(t, R, label='Recovered', color='green')
    plt.plot(t, D, label='Deceased', color='red')
    plt.xlabel('Hari')
    plt.ylabel('Jumlah individu')
    plt.title('Simulasi Model SIRD')
    plt.legend()
    plt.grid()
    plt.show()

widgets.interactive(update_sird,
    beta=widgets.FloatSlider(min=0.0001, max=1, step=0.0001, value=0.2, description='β'),
    gamma=widgets.FloatSlider(min=0.01, max=1, step=0.01, value=0.1, description='γ'),
    mu=widgets.FloatSlider(min=0.0001, max=0.1, step=0.0001, value=0.01, description='μ'),
    S0=widgets.IntSlider(min=1, max=1000, step=1, value=990, description='S₀'),
    I0=widgets.IntSlider(min=1, max=100, step=1, value=10, description='I₀'),
    Tmax=widgets.IntSlider(min=10, max=200, step=1, value=100, description='T max'))