# -*- coding: utf-8 -*-
"""TUGAS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3ibuU969ADiSH6-qInAW1_NPltWA2NA
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter Model
beta = 0.3     # Laju infeksi
alpha = 0.2    # Laju individu berpindah dari E ke I
gamma = 0.1    # Laju pemulihan atau manajemen diabetes
mu = 0.01      # Laju kelahiran dan kematian alami
N = 1000       # Total populasi

# Persamaan Diferensial Model SEIR dengan Kelahiran dan Kematian
def seir_model(y, t, beta, alpha, gamma, mu):
    S, E, I, R = y
    dSdt = mu * N - beta * S * I / N - mu * S
    dEdt = beta * S * I / N - alpha * E - mu * E
    dIdt = alpha * E - gamma * I - mu * I
    dRdt = gamma * I - mu * R
    return [dSdt, dEdt, dIdt, dRdt]

# Kondisi Awal
S0 = 990  # Individu rentan
E0 = 5    # Individu terpapar
I0 = 5    # Individu dengan diabetes
R0 = 0    # Individu sembuh

y0 = [S0, E0, I0, R0]

# Waktu Simulasi
t = np.linspace(0, 200, 200)

# Simulasi dengan odeint
sol = odeint(seir_model, y0, t, args=(beta, alpha, gamma, mu))

# Plot hasil
plt.figure(figsize=(10, 6))
plt.plot(t, sol[:, 0], label='S (Rentan)', color='blue')
plt.plot(t, sol[:, 1], label='E (Terpapar)', color='orange')
plt.plot(t, sol[:, 2], label='I (Diabetes)', color='red')
plt.plot(t, sol[:, 3], label='R (Sembuh)', color='green')
plt.xlabel('Waktu (Hari)')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR dengan Kelahiran dan Kematian untuk Diabetes Mellitus Tipe 2')
plt.legend()
plt.grid()
plt.show()