# -*- coding: utf-8 -*-
"""nilai eigen dan vektor eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMXgjFrx4q3wrXBWUTpVK_JIEijAj1LM
"""

import numpy as bag

A = bag.array([[4,1],
               [2,3]])
nilaieigen, vektoreigen = bag.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

A = bag.array([[2,7],
               [-2,-1]])
nilaieigen, vektoreigen = bag.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)