# -*- coding: utf-8 -*-
"""pertumbuhan logistik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IEXMMZQlDXrFxZEDb_JkUGnaDhKD5Qrx
"""

import numpy as np
import matplotlib.pyplot as plt

def logistic_growth(P0, r, K, t_max, dt=0.1):
    """
    Simulasi pertumbuhan logistik menggunakan metode numerik Euler.

    Parameters:
    P0 : float - Populasi awal
    r  : float - Laju pertumbuhan intrinsik
    K  : float - Kapasitas dukung lingkungan
    t_max : float - Waktu maksimum simulasi
    dt : float - Interval waktu (default 0.1)

    Returns:
    t_values : array - Waktu
    P_values : array - Populasi pada setiap waktu
    """
    t_values = np.arange(0, t_max, dt)
    P_values = np.zeros_like(t_values)
    P_values[0] = P0

    for i in range(1, len(t_values)):
        dP_dt = r * P_values[i-1] * (1 - P_values[i-1] / K)
        P_values[i] = P_values[i-1] + dP_dt * dt

    return t_values, P_values

# Parameter model
P0 = 100   # Populasi awal
r = 0.2    # Laju pertumbuhan
K = 1000   # Kapasitas dukung
t_max = 50 # Waktu maksimum

# Menjalankan simulasi
t, P = logistic_growth(P0, r, K, t_max)

# Visualisasi hasil
plt.figure(figsize=(8,5))
plt.plot(t, P, label='Pertumbuhan Logistik', color='blue')
plt.axhline(K, linestyle='--', color='r', label='Kapasitas Dukung')
plt.xlabel('Waktu')
plt.ylabel('Populasi')
plt.title('Simulasi Pertumbuhan Logistik')
plt.legend()
plt.grid()
plt.show()