# -*- coding: utf-8 -*-
"""pratikum pelonjakan hiv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14O9CQiKNXrSl3eraRn74WYIAvqmK9Q_e
"""

import numpy as np
import matplotlib.pyplot as plt

#parameter model
N = 1000
beta = 0.002
ganma = 0.1
mu = 0.01
delta = 0.2

# kondisi awal
H0 = 900
I0 = 80
V0 = 20

# waktu simulasi
T = 100
dt = 1

# vektor waktu
time = np.arange(0 , T + dt, dt)

# array untuk menyimpan hasil simulasi
H = np.zeros(len(time))
I = np.zeros(len(time))
V = np.zeros(len(time))

# inisialisasi ondisi awal
H[0] = H0
I[0] = I0
V[0] = I0

#simulasi dengan metode euler
for t in range(1, len(time)):
   dH = mu * N - beta * H[t-1] * I[t-1] - mu * H[t-1]
   dI = beta * H[t-1] * I[t-1] - (ganma + mu) * I[t-1]
   dV = ganma * I[t-1] - (delta + mu) * V[t-1]

   # update populasi
   H[t] = H[t-1] + dH * dt
   I[t] = I[t-1] + dI * dt
   V[t] = V[t-1] + dV * dt

# plot hasil simulasi
plt.figure(figsize=(10 , 6))
plt.plot(time ,H, label='Rentan (H)',color='blue')
plt.plot(time ,I, label='Terinfeksi HIV (I)',color='orange')
plt.plot(time ,V, label='AIDS (V)', color='red')

plt.title('simulasi penyebaran HIV selama 100 ari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Populasi')
plt.legend()
plt.grid(True)
plt.show()