# -*- coding: utf-8 -*-
"""rusa dan serigala.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTHdyKGfKLiC69JUJEW8s7nGrs2H2FtD
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# parameter model
alpha = 0.5
beta = 0.02
delta = 0.01
ganma = 0.3

# persamaan diferensial lotka-volterra
def lotka_volterra(y, t, alpha, beta, delta, ganma):
    x, y = y
    dxdt = alpha * x - beta * x * y
    dydt = delta * x * y - ganma * y
    return [dxdt, dydt]

# kondisi awal: jumlah awal rusa dan serigala
y0 = [40, 9]

# rentang waktu simulasi (0 sampai 100 unit waktu)
t = np.linspace(0, 200, 1000)

# menyelesaikan persamaan diferensial
solution = odeint(lotka_volterra, y0, t, args=(alpha, beta, delta, ganma))
rusa, serigala = solution.T

# membuat grafik hasil simulasi
plt.figure(figsize=(10, 5))
plt.plot(t, rusa, label="rusa (prey)", color="pink", linewidth=2)
plt.plot(t, serigala, label="serigala (predator)", color="magenta", linewidth=2)
plt.xlabel("waktu")
plt.ylabel("populasi")
plt.title("simulasi model lotka-volterra: rusa vs serigala")
plt.legend()
plt.grid()
plt.show()